#!/bin/bash
set -e

case "$1" in
  remove|abort-install)
    if [ -x /usr/sbin/update-alternatives ]; then
      update-alternatives --remove hurl /usr/bin/hurl 2>/dev/null || true
    fi
    ;;
  purge)
    if [ -x /usr/sbin/update-alternatives ]; then
      update-alternatives --remove hurl /usr/bin/hurl 2>/dev/null || true
    fi
    ;;
  upgrade|failed-upgrade|abort-upgrade|disappear)
    ;;
  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
