#!/bin/bash
set -e

case "$1" in
  install|upgrade)
    if [ -x /usr/bin/hurl ]; then
      /usr/bin/hurl --version >/dev/null 2>&1 || true
    fi
    ;;
  abort-remove)
    ;;
  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
