[alias]
build-release = "build --release"
build-debug = "build --debug"
check-all = "check --all-targets --all-features"
fmt-check = "fmt -- --check"
lint = "clippy --all-targets --all-features -- -W clippy::all"

[build]
jobs = 4
rustflags = ["-C", "overflow-checks=on"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"

[profile.release.package."*"]
opt-level = 3
debug = false

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "packed"

[profile.test]
opt-level = 1

[profile.bench]
inherits = "release"
debug = true

[net]
retry = 3
git-fetch-with-cli = false

[term]
color = "auto"
verbose = false
